-- 001_init.sql
-- Metadata only. Datasets, weights and GGUF live on the workspace filesystem.
-- Schema follows 改造开发方案.md section 7.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version     INTEGER PRIMARY KEY,
    script      TEXT    NOT NULL,
    applied_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    description  TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    -- Soft delete: 需求方案.txt principle 5 requires 7-day recovery.
    deleted_at   TEXT
);

CREATE TABLE IF NOT EXISTS runs (
    id                   TEXT PRIMARY KEY,
    project_id           TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,

    scene_code           TEXT,
    mode                 TEXT NOT NULL DEFAULT 'wizard',
    state                TEXT NOT NULL,

    dataset_id           TEXT,
    split_id             TEXT,
    synth_id             TEXT,

    base_model_id        TEXT,
    training_config_json TEXT,

    job_id               TEXT,
    model_version_id     TEXT,
    evaluation_id        TEXT,
    deployment_id        TEXT,

    error_message        TEXT,
    created_at           TEXT NOT NULL,
    updated_at           TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_runs_project ON runs(project_id);
CREATE INDEX IF NOT EXISTS idx_runs_state   ON runs(state);

CREATE TABLE IF NOT EXISTS datasets (
    id                 TEXT PRIMARY KEY,
    run_id             TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,

    code               TEXT NOT NULL,
    original_filename  TEXT NOT NULL,
    source_path        TEXT NOT NULL,

    rows               INTEGER NOT NULL DEFAULT 0,
    cols               INTEGER NOT NULL DEFAULT 0,
    label_column       TEXT,
    label_mapping_json TEXT,

    checksum           TEXT NOT NULL,
    status             TEXT NOT NULL,
    created_at         TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_datasets_run ON datasets(run_id);

CREATE TABLE IF NOT EXISTS dataset_splits (
    id           TEXT PRIMARY KEY,
    dataset_id   TEXT NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    run_id       TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,

    code         TEXT NOT NULL,

    train_path   TEXT NOT NULL,
    valid_path   TEXT NOT NULL,
    test_path    TEXT NOT NULL,

    train_rows   INTEGER NOT NULL,
    valid_rows   INTEGER NOT NULL,
    test_rows    INTEGER NOT NULL,

    -- Hard constraint from 需求方案.txt 5.4: synthetic rows never reach test.
    -- Stored so it is auditable rather than merely asserted in passing.
    test_synth_rows INTEGER NOT NULL DEFAULT 0,
    quality_json     TEXT,

    created_at   TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_splits_run ON dataset_splits(run_id);

CREATE TABLE IF NOT EXISTS synth_runs (
    id              TEXT PRIMARY KEY,
    run_id          TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    dataset_id      TEXT NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,

    code            TEXT NOT NULL,
    method          TEXT NOT NULL,
    config_json     TEXT,

    output_path     TEXT NOT NULL,
    rows            INTEGER NOT NULL,
    checksum        TEXT NOT NULL,

    fidelity_score  REAL,
    privacy_json    TEXT,

    status          TEXT NOT NULL,
    created_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_synth_run ON synth_runs(run_id);

CREATE TABLE IF NOT EXISTS jobs (
    id              TEXT PRIMARY KEY,
    run_id          TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,

    type            TEXT NOT NULL,
    status          TEXT NOT NULL,

    progress        INTEGER NOT NULL DEFAULT 0,
    stage           TEXT,
    message         TEXT,

    payload_json    TEXT,
    result_json     TEXT,

    pid             INTEGER,
    log_path        TEXT,
    -- Recorded when a worker takes a job and dies without finishing it, so the
    -- UI can distinguish interrupted from failed.
    claimed_at      TEXT,

    error_message   TEXT,
    created_at      TEXT NOT NULL,
    started_at      TEXT,
    finished_at     TEXT
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_run    ON jobs(run_id);

CREATE TABLE IF NOT EXISTS model_versions (
    id                 TEXT PRIMARY KEY,
    run_id             TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,

    code               TEXT NOT NULL,
    base_model_id      TEXT NOT NULL,
    training_method    TEXT NOT NULL,

    adapter_path       TEXT,
    merged_model_path  TEXT,

    -- Generated by the system from the run's own records. Never supplied by a
    -- client: 改造开发方案.md 18.
    lineage_json       TEXT,

    created_at         TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mv_run ON model_versions(run_id);

CREATE TABLE IF NOT EXISTS artifacts (
    id                TEXT PRIMARY KEY,
    model_version_id  TEXT NOT NULL REFERENCES model_versions(id) ON DELETE CASCADE,

    type              TEXT NOT NULL,
    format            TEXT NOT NULL,
    quant             TEXT,

    path              TEXT NOT NULL,
    checksum          TEXT,
    bytes             INTEGER,

    created_at        TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_artifacts_mv ON artifacts(model_version_id);

CREATE TABLE IF NOT EXISTS evaluations (
    id                   TEXT PRIMARY KEY,
    run_id               TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    model_version_id     TEXT NOT NULL REFERENCES model_versions(id) ON DELETE CASCADE,

    test_dataset_path    TEXT NOT NULL,
    predictions_path     TEXT,
    error_cases_path     TEXT,

    -- Null when nothing was measured. Never defaulted to a number.
    metrics_json         TEXT,
    performance_json     TEXT,

    created_at           TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_evaluations_mv ON evaluations(model_version_id);

CREATE TABLE IF NOT EXISTS deployments (
    id                TEXT PRIMARY KEY,
    run_id            TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
    model_version_id  TEXT NOT NULL REFERENCES model_versions(id) ON DELETE CASCADE,
    artifact_id       TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,

    runtime           TEXT NOT NULL,
    host              TEXT NOT NULL,
    port              INTEGER NOT NULL,
    pid               INTEGER,

    -- SERVING only after a real health check, per Rule 6.
    status            TEXT NOT NULL,
    log_path          TEXT,

    started_at        TEXT,
    stopped_at        TEXT,
    created_at        TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_deployments_mv ON deployments(model_version_id);

CREATE TABLE IF NOT EXISTS audit_log (
    id         TEXT PRIMARY KEY,
    actor      TEXT NOT NULL,
    action     TEXT NOT NULL,
    target     TEXT NOT NULL,
    detail     TEXT,
    ts         TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_ts ON audit_log(ts);