#!/usr/bin/env python
"""Generate TypeScript types for apps/web from the control-plane OpenAPI document.

`libs/contracts` Pydantic models are the single source of truth for anything
crossing a service boundary, so the web client's types are generated rather than
hand-written. Run from the repo root:

    uv run python tools/gen_openapi_types.py

The output is committed so `npm run typecheck` works without a running API.
Regenerate it whenever a contract changes and commit the diff alongside.
"""

from __future__ import annotations

import json
import keyword
import re
from pathlib import Path
from typing import Any

from son_api.main import create_app

OUT_DIR = Path("apps/web/src/api/generated")

# Pydantic emits JSON-Schema-ish constructs that are meaningless in TS output.
_UNSUPPORTED = re.compile(r"^(additionalProperties|discriminator|xml|externalDocs|examples)$")


def _ts_name(name: str) -> str:
    """Convert a schema key into a safe PascalCase TypeScript identifier."""
    cleaned = re.sub(r"[^0-9a-zA-Z]+", " ", name).title().replace(" ", "")
    if not cleaned:
        return "Schema"
    if cleaned[0].isdigit():
        cleaned = f"Schema{cleaned}"
    return cleaned


def _ts_type(schema: dict[str, Any]) -> str:
    if not schema:
        return "unknown"
    for combinator in ("anyOf", "oneOf", "allOf"):
        if combinator in schema:
            parts = [_ts_type(s) for s in schema[combinator]]
            # Deduplicate while preserving order, e.g. the Decision enum.
            unique = list(dict.fromkeys(parts))
            return unique[0] if len(unique) == 1 else " | ".join(unique)
    if "const" in schema:
        return "null" if schema["const"] is None else _ts_literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_ts_enum_member(v) for v in schema["enum"])
    ref = schema.get("$ref")
    if ref:
        # Apply the same name transform used for declarations, otherwise a
        # reference to `JevFlags` points at a type emitted as `Jevflags`.
        return _ts_name(ref.rsplit("/", 1)[-1])
    if "type" in schema:
        types = schema["type"]
        types = types if isinstance(types, list) else [types]
        mapped = [_PRIMITIVES.get(t, "unknown") for t in types]
        return " | ".join(dict.fromkeys(mapped))
    return "unknown"


_PRIMITIVES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
    "object": "Record<string, unknown>",
    "array": "unknown[]",
}


def _ts_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if keyword.iskeyword(text) or not re.fullmatch(r"[A-Za-z_$][\w$]*", text):
        return json.dumps(text, ensure_ascii=False)
    return text


def _ts_enum_member(value: Any) -> str:
    """Enum members are values, not identifiers.

    A bare `black` would type-check as an undefined reference, so every string
    member is emitted as a quoted literal regardless of how identifier-like it
    looks.
    """
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return _ts_literal(value)


def _collect(schemas: dict[str, Any]) -> dict[str, str]:
    out: dict[str, str] = {}
    for name, schema in schemas.items():
        if _UNSUPPORTED.match(name):
            continue
        type_name = _ts_name(name)
        required = set(schema.get("required", []))
        props = schema.get("properties", {})
        if not props:
            out[type_name] = f"export type {type_name} = {_ts_type(schema)};\n"
            continue
        lines = [f"export interface {type_name} {{"]
        for prop, prop_schema in props.items():
            optional = "" if prop in required else "?"
            field = f'"{prop}"' if not re.fullmatch(r"[A-Za-z_$][\w$]*", prop) else prop
            doc = prop_schema.get("description")
            if doc:
                lines.append(f"  /** {doc} */")
            lines.append(f"  {field}{optional}: {_ts_type(prop_schema)};")
        lines.append("}")
        out[type_name] = "\n".join(lines) + "\n"
    return out


HEADER = """// AUTO-GENERATED by tools/gen_openapi_types.py - do not edit by hand.
//
// Source: apps/api OpenAPI document, derived from the Pydantic contracts in
// libs/contracts. Regenerate with:
//   uv run python tools/gen_openapi_types.py
"""


def main() -> None:
    spec = create_app().openapi()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    spec_path = OUT_DIR / "openapi.json"
    spec_path.write_text(json.dumps(spec, ensure_ascii=False, indent=2), encoding="utf-8")

    types = _collect(spec.get("components", {}).get("schemas", {}))
    body = "\n".join(types[k] for k in sorted(types))
    (OUT_DIR / "types.ts").write_text(f"{HEADER}\n{body}", encoding="utf-8")

    print(f"wrote {spec_path}")
    print(f"wrote {OUT_DIR / 'types.ts'} ({len(types)} schemas)")


if __name__ == "__main__":
    main()
